#!/bin/bash
if [ -z "$(pwd)/gadget" ]; then
	echo "You seem to be running this from the wrong directory."
	echo "Please run from the gadget-os git root."
	exit 1
fi

docker build -f scripts/Dockerfile -t gadget-build-container $(pwd)

docker volume inspect gadget-build-ccache > /dev/null
if [ ! "$?" == "0" ]; then
	docker volume create --name gadget-build-ccache
fi
docker volume inspect gadget-build-output > /dev/null
if [ ! "$?" == "0" ]; then
	docker volume create --name gadget-build-output
fi
docker volume inspect gadget-build-dlcache > /dev/null
if [ ! "$?" == "0" ]; then
	docker volume create --name gadget-build-dlcache
fi