#!/bin/sh
if [ -n "${1}" ]; then
	task="${@}"
else
	task="make"
fi

GADGET_DIR="$(pwd)/"
IMAGE_DIR="$(pwd)/output/images"
GADGET_CONTAINER=${GADGET_CONTAINER:-gadget-build-container}
ENVIRONMENT_FILE=".local-env"

INTERACTIVE=""
if [ -n "${TERM}" ]; then
	INTERACTIVE="-it"
fi

if [ -z "${GADGET_DIR}/gadget" ] || [ -z "${IMAGE_DIR}" ]; then
	echo "You seem to be running this from the wrong directory."
	echo "Please run from the gadget-os git root."
	exit 1
fi

LOCAL_ENV=""
if [ -f "${ENVIRONMENT_FILE}" ]; then
	echo "Using local environment: ${ENVIRONMENT_FILE}"
	LOCAL_ENV="--env-file ${ENVIRONMENT_FILE}"
fi


docker run \
	--rm \
	--env BR2_DL_DIR=/opt/dlcache/ \
	--env SSH_AUTH_SOCK=${SSH_AUTH_SOCK} \
	--volume=${SSH_AUTH_SOCK} \
	--volume=gadget-build-dlcache:/opt/dlcache/ \
	--volume=gadget-build-output:/opt/output \
	--volume=${IMAGE_DIR}:/opt/output/images \
	--volume=${GADGET_DIR}:/opt/gadget-os-proto \
	--name=gadget-build-task \
	-w="/opt/gadget-os-proto" \
	${LOCAL_ENV} \
	${INTERACTIVE} \
	${GADGET_CONTAINER} \
	${task}


#	--env BR2_CCACHE_DIR=/opt/ccache/ \
#	--volume=gadget-build-ccache:/opt/ccache/ \