#!/bin/bash

echo "Installing sunxi-tools and android-tools-fastboot"
sudo apt-get -y install sunxi-tools android-tools-fastboot

echo "Adding user ${USER} to dialout and plugdev groups"
sudo usermod -a -G dialout ${USER}
sudo usermod -a -G plugdev ${USER}

echo "Create udev rules"
echo -e 'SUBSYSTEM=="usb", ATTRS{idVendor}=="1f3a", ATTRS{idProduct}=="efe8",       GROUP="plugdev", MODE="0660" SYMLINK+="usb-chip"
SUBSYSTEM=="usb", ATTRS{idVendor}=="18d1", ATTRS{idProduct}=="1010", GROUP="plugdev",   MODE="0660" SYMLINK+="usb-chip-fastboot"
SUBSYSTEM=="usb", ATTRS{idVendor}=="1f3a", ATTRS{idProduct}=="1010", GROUP="plugdev",   MODE="0660" SYMLINK+="usb-chip-fastboot"
SUBSYSTEM=="usb", ATTRS{idVendor}=="067b", ATTRS{idProduct}=="2303", GROUP="plugdev",   MODE="0660" SYMLINK+="usb-serial-adapter"
' | sudo tee /etc/udev/rules.d/99-allwinner.rules
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Please log out and in again!"
