#!/bin/sh

# include script lib
SCRIPTDIR="$( cd "$( dirname "$0" )" && pwd )"
. "$SCRIPTDIR/gadget_update_lib"

mutex /var/run/update_requester

echo -e "\nUPDATE_REQUESTER\n"

[[ ! -x $(which curl) ]] && fatal "ERROR: cannot find curl"
[[ ! -x $(which jq) ]] && fatal "ERROR: cannot find jq"
[[ ! -x $(which sha256sum) ]] && fatal "ERROR: cannot find sha256sum"

SYSTEM_CFG="/etc/gadget-update/system.cfg"
[[ -z "${SYSTEM_CFG}" ]] && echo "SYSTEM_CFG is not set" && exit 1
echo "reading system configuration..."
[[ ! -f "${SYSTEM_CFG}" ]] && echo "ERROR: cannot read \"$SYSTEM_CFG\"" && exit 1
! read_cfg cfg "${SYSTEM_CFG}" && echo "ERROR" && exit 1

URL="${cfg_system_server_url}"
WORKDIR="${cfg_system_workdir}"
MANIFEST="$WORKDIR/manifest"

[[ ! -d $WORKDIR ]] && ! mkdir -p "$WORKDIR" && fatal "ERROR: cannot create directory '$WORKDIR'"

## REQUEST UPDATE
echo -n "Requesting update from $URL..."
! curl -so "$MANIFEST" $URL && fatal
echo "OK"

## UPDATE AVAILABLE?
N_ARTIFACTS=$( jq '.Artifacts | length' <$MANIFEST )
#N_ARTIFACTS=$( echo 'hello' | jq '.Artifacts | length' 2>/dev/null)
[[ -z "$N_ARTIFACTS" ]] && fatal "No update available."
[[ "$N_ARTIFACTS" -le "1" ]] && fatal "No update available."
echo "Number of Artifacts: $N_ARTIFACTS"

## VERIFY UPDATE
### TODO: proper signature verification here!
echo -n "Verifying signature..."
SIGNATURE="$(cat "$MANIFEST"| jq -r '.Signature')"
VERIFY="$(cat "$MANIFEST" |jq -cM '.Artifacts' |sha256sum)"
VERIFY="${VERIFY%% *}"
[[ "$SIGNATURE" != "$VERIFY" ]] && fatal "ERROR: invalid signature"
echo "OK"

## APPLY UPDATE
updater "$MANIFEST"
