#!/bin/sh


# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
for i in $(ls -r /etc/init.d/S??*) ;do

	 # Ignore dangling symlinks (if any).
	 [ ! -f "$i" ] && continue

	# No sh extension, so fork subprocess.
	$i stop
done

