#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

	 # Ignore dangling symlinks (if any).
	 [ ! -f "$i" ] && continue

	# No sh extension, so fork subprocess.
	nohup $i start &
done

