#!/bin/sh

MODPROBE=/sbin/modprobe
RETVAL=0

start() {
	/bin/stty -F /dev/ttyS1 115200
	# /bin/stty -F /dev/ttyGS0 115200
}

stop() {
	echo "Nothing to do"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status $processname
		RETVAL=$?
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		;;
esac
exit $RETVAL
