#!/bin/sh
RETVAL=0

start() {
	/bin/mount -t proc proc /proc
	/bin/mount -o remount,rw /
	/bin/mkdir -p /dev/pts
	/bin/mkdir -p /dev/shm
	/bin/mount -a
	/bin/hostname -F /etc/hostname
	/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
	/sbin/mdev -s
}

stop() {
}
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $processname
        RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        ;;
esac
exit $RETVAL
